# Pandas Datatype

In [2]:
import pandas as pd

##### Series : 1 Dimensional

In [3]:
cars =pd.Series(["Nissan", "Volvo", "Toyota", "Honda"]);
colours =pd.Series(["yellow", "green", "black", "orange"])
cars, colours

(0    Nissan
 1     Volvo
 2    Toyota
 3     Honda
 dtype: object,
 0    yellow
 1     green
 2     black
 3    orange
 dtype: object)

In [4]:
# Indexing
cars[2] , cars[0]

('Toyota', 'Nissan')

##### Data Frames : 2 Dimensional

In [5]:
car_data = pd.DataFrame({"Brand":cars, "Colour":colours})
car_data

    Brand  Colour
0  Nissan  yellow
1   Volvo   green
2  Toyota   black
3   Honda  orange

##### Importing a CSV file and turning it into a data frame

In [7]:
cars_data = pd.read_csv("car-sales.csv")
cars_data

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

##### Exporting data to a new CSV file

In [9]:
car_data.to_csv("car_data_exported.csv")